# Generated by Django 2.0.3 on 2018-04-03 12:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Images',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('imageMain', models.FileField(upload_to='')),
                ('votes', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('productName', models.CharField(max_length=250)),
                ('productGenre', models.CharField(max_length=250)),
                ('productGroup', models.CharField(max_length=250)),
                ('productSize', models.CharField(max_length=250)),
                ('productDescript', models.CharField(max_length=250)),
                ('productPublish', models.DateTimeField(verbose_name='date published')),
            ],
        ),
        migrations.AddField(
            model_name='images',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='products.Product'),
        ),
    ]
