# Generated by Django 2.0.3 on 2018-04-09 19:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0002_auto_20180407_1121'),
    ]

    operations = [
        migrations.AlterField(
            model_name='image',
            name='imageMain',
            field=models.FileField(blank=True, null=True, upload_to=''),
        ),
    ]
