# Generated by Django 2.0.3 on 2018-06-10 07:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0003_auto_20180409_1944'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='productImage',
            field=models.FileField(blank=True, null=True, upload_to=''),
        ),
    ]
