# Generated by Django 2.0.13 on 2019-06-07 07:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0007_sliderimage'),
    ]

    operations = [
        migrations.AddField(
            model_name='sliderimage',
            name='active',
            field=models.BooleanField(default=True),
        ),
    ]
