# Generated by Django 2.0.13 on 2019-06-09 12:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0008_sliderimage_active'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='sliderimage',
            name='product',
        ),
        migrations.DeleteModel(
            name='SliderImage',
        ),
    ]
