# Generated by Django 2.2.3 on 2019-07-16 19:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0010_email'),
    ]

    operations = [
        migrations.AlterField(
            model_name='email',
            name='created',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
