# Generated by Django 2.2.3 on 2019-07-17 10:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0011_auto_20190716_2357'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='email',
            name='created',
        ),
    ]
