# Generated by Django 2.2.3 on 2019-08-07 10:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0012_remove_email_created'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='productGenre',
            field=models.CharField(choices=[('men', 'Men'), ('women', 'Women')], default='women', max_length=50),
        ),
        migrations.AlterField(
            model_name='product',
            name='productGroup',
            field=models.CharField(choices=[('handbag', 'Handbag'), ('backpack', 'Backpack'), ('purse', 'Purse'), ('accessory', 'Accessory'), ('bag', 'Bag'), ('briefcase', 'Briefcase'), ('wallet', 'Wallet')], default='handbag', max_length=250),
        ),
    ]
