# Generated by Django 2.2.3 on 2019-08-07 11:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0013_auto_20190807_1518'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='productSizeD',
            field=models.IntegerField(blank=True, null=True, verbose_name='Depth'),
        ),
        migrations.AddField(
            model_name='product',
            name='productSizeH',
            field=models.IntegerField(blank=True, null=True, verbose_name='Height'),
        ),
        migrations.AddField(
            model_name='product',
            name='productSizeW',
            field=models.IntegerField(blank=True, null=True, verbose_name='Width'),
        ),
    ]
