# Generated by Django 2.2.3 on 2019-08-11 05:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0021_auto_20190811_0931'),
    ]

    operations = [
        migrations.AddField(
            model_name='slider',
            name='active',
            field=models.BooleanField(default=True),
        ),
    ]
