# Generated by Django 2.2.3 on 2019-08-11 06:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0022_slider_active'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='productPublish',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
