# Generated by Django 2.2.3 on 2019-08-11 09:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0025_auto_20190811_1124'),
    ]

    operations = [
        migrations.AddField(
            model_name='slider',
            name='product',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='products.Product'),
        ),
    ]
