# Generated by Django 2.2.3 on 2019-09-07 07:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0027_auto_20190811_1435'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='productSize',
        ),
    ]
